# Generated by Django 5.2.5 on 2025-08-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
    ]
